### ISSUE TITLE
Add Carthage support

### ISSUE THREAD

**Issue by marcosgriselli** [marcosgriselli/ViewAnimator#11]
👆

**Comment by TofPlay** [comment]
Hi,
Here some articles that will help you: 
- [Ruthlessly Simple Dependency Management with Carthage](https://goo.gl/8AMTfw)
- [Carthage Tutorial: Getting Started](https://goo.gl/DsFf6x)
- [Making Carthage-compatible Frameworks with Swift](https://goo.gl/SzPe8j)
- [Swift Cross Platform Framework](https://goo.gl/XxaJGo) 👍
