### ISSUE TITLE
Problems appearing cells before the animation starts.

### ISSUE THREAD

**Issue by alexanderkhitev** [marcosgriselli/ViewAnimator#12]
Hello! Thanks for the wonderful framework! I ran into the problem that UICollectionView cells appear before the animation starts, at this point the cells are loading photos and the user names are already visible. Please tell me how can this be avoided?

```self?.userLocationModels = userLocationModels
                self?.collectionView.refreshControl?.endRefreshing()
                let offset = UIScreen.main.bounds.width
                let fromAnimation = AnimationType.from(direction: .left, offset: offset)
                let animationInterval = 0.1
                self?.collectionView.animateViews(animations: [fromAnimation], initialAlpha: 1, finalAlpha: 1, delay: 0, duration: 0.4, animationInterval: animationInterval, completion: {
                    
                })
                self?.collectionView.reloadData()
````
https://monosnap.com/file/MgYyNwEbBqeMdyI4jedYBPMf0uIKOQ

![1](https://user-images.githubusercontent.com/12511909/32325657-50666e7a-bfe9-11e7-820e-e15b69da8b98.png)

**Comment by marcosgriselli** [comment]
If you're animating from outside the view I recommend you hide the views then reload the data and then apply the animation. 

```swift 
self?.collectionView.refreshControl?.endRefreshing()
let offset = UIScreen.main.bounds.width
self?.collectionView.prepareViews()
self?.collectionView.reloadData()
let fromAnimation = AnimationType.from(direction: .left, offset: offset)
let animationInterval = 0.1
self?.collectionView.animateViews(animations: [fromAnimation], initialAlpha: 1, finalAlpha: 1, delay: 0, duration: 0.4, animationInterval: animationInterval, completion: {
                    
})
```

**Comment by alexanderkhitev** [comment]
Hello @marcosgriselli ! I tried to do so it did not help me.

Also I did so, but it did not help me
```
self?.collectionView.prepareViews(initialAlpha: 0)
self?.collectionView.reloadData()
```

**Comment by marcosgriselli** [comment]
@alexanderkhitev prepareViews will not work if there are no cells to prepare 😕. You'll have to do some workaround. The shortest path to get it could be 
``` swift 
self?.collectionView.alpha = 0
self?.collectionView.reloadData()
self?.collectionView.prepareViews(initialAlpha: 0)
self?.collectionView.alpha = 1
``` 

Or setting te cell alpha to 0 on `cellForItem()` only for the first load.

**Comment by alexanderkhitev** [comment]
@marcosgriselli Yes I tried doing the same method only with isHidden and it also works, thanks!
