### ISSUE TITLE
Cannot install as pod

### ISSUE THREAD

**Issue by evanzombie** [marcosgriselli/ViewAnimator#15]
## Expected Behavior
Install through pod install

## Actual Behavior
[!] Unable to find a specification for `ViewAnimator`
[!] Unable to find a specification for `ViewAnimator (~> 1.0)`
[!] Unable to find a specification for `ViewAnimator (~> 1.0.2)`

**Comment by marcosgriselli** [comment]
That's an issue with your spec repo, you'll need to run `pod repo update`. 

You can read more about it in CocoaPods/CocoaPods#3877.

**Comment by evanzombie** [comment]
Thank you. Running` pod repo update` makes it work.
