### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by ianbytchek** [marcosgriselli/ViewAnimator#19]
Please consider! ❤️

**Comment by marcosgriselli** [comment]
This could be interesting. I don't have prior AppKit experience but it could be a good place to start. Honestly I have no idea about how AppKit UI elements API's are designed but I'll take a look.

**Comment by marcosgriselli** [comment]
I'll be closing this for now but I'll have it on a _Someday_ list.

**Comment by PublicWorld** [comment]
> I'll be closing this for now but I'll have it on a _Someday_ list.

@marcosgriselli 
Thank you. 
I want to ask how long it will take for this day to come. I've been waiting for 5 years.

**Comment by marcosgriselli** [comment]
@PublicWorld thanks for getting interested in that feature but as of now I don't have plans to support this.
