### ISSUE TITLE
EXC_BREAKPOINT in animateViews 

### ISSUE THREAD

**Issue by truemetal** [marcosgriselli/ViewAnimator#27]
Hey

The issue happens right here, in my case `dispatchGroup.leave()` happens more times then `dispatchGroup.enter()` which causes `EXC_BREAKPOINT`

Probably, subviews count changes during `asyncAfter`

The code, invoked the animation is this: 
```
let fromAnimation = AnimationType.from(direction: .right, offset: 400.0)   
animateViews(animations: [fromAnimation], initialAlpha: 0.0, finalAlpha: 1.0, delay: 0.0, duration: 0.2, animationInterval: 0.2, completion: nil)
```

Cheers

![animatable_swift](https://user-images.githubusercontent.com/2472186/37086479-5ac9ab10-2200-11e8-9354-76e836016393.png)

**Comment by marcosgriselli** [comment]
Closed by #28
