### ISSUE TITLE
CollecitonView `animateViews` for `indexPaths`

### ISSUE THREAD

**Issue by KaushalElsewhere** [marcosgriselli/ViewAnimator#32]
hi, thanks for your awesome framework.
Is there any way to `animateViews` of collectionView for a set of indexPath ie. Array of IndexPath.
I have pagination on my collection view and every time I append items on it the whole collection view starts animating ( which I don't want). 
I just wanted to animate for a selected array of index paths.
Cheers.

**Comment by marcosgriselli** [comment]
This issue will be handled by #33 as it will target animating sections or indexPaths for both `UICollectionView` and `UITableView`.
