### ISSUE TITLE
restoreViewsToIdentity() by default

### ISSUE THREAD

**Issue by dillidon** [marcosgriselli/ViewAnimator#46]
I think, implementation `restoreViewsToIdentity()` on reverse should be by default. Are there any cases to use hidden view after reversed animation below its necessary position?

**Comment by marcosgriselli** [comment]
`restoreViewsToIdentity()` method was removed a few releases ago as we don't want to be removing any external transforms added to the views, we just want to handle the transform exactly before the animation starts and add our animations.
