### ISSUE TITLE
sprintWithDamping/initialSpringVelocity not working?

### ISSUE THREAD

**Issue by haemi** [marcosgriselli/ViewAnimator#59]
## Expected Behavior
when setting `usingSpringWithDamping` and `initialSpringVelocity` it seems as if they have no effect; no spring animation at all... Am I missing something?

## Actual Behavior
E.g. the zoom animation is linear, the view grows - but now springin

## Steps to Reproduce the Problem

  1. setting `usingSpringWithDamping` to e.g. 3, 0.3, ...
  1. setting `initialSpringVelocity` to e.g. 5, 0.5, ...
  1. there is no difference between setting in on configuration or directly with `UIView.animate`

## Specifications

  - Version: 13
  - Platform: iOS

**Comment by marcosgriselli** [comment]
Hi @haemi, thanks for reporting this. I'll take a look at it on the upcoming days.

**Comment by marcosgriselli** [comment]
@haemi, the springs are working as expected. 

I'm using these values to create the animation below: 

```swift 
UIView.animate(
    views: self.collectionView!.orderedVisibleCells,
    animations: animations,
    duration: 1.3,
    usingSpringWithDamping: 0.45,
    initialSpringVelocity: 10
)
```

![Screen Recording 2019-10-12 at 16 35 20](https://user-images.githubusercontent.com/14804033/66706837-8ba9d900-ed0e-11e9-93e3-8d0de11e0903.gif)

Perhaps your animation uses the default `duration` and it's to fast to appreciate the spring? 
Also, keep in mind that `usingSpringWithDamping` goes from 0 to 1.
