### ISSUE TITLE
Animations don't work when presenting a ViewController

### ISSUE THREAD

**Issue by d0hnj0e** [marcosgriselli/ViewAnimator#64]
## Expected Behavior
Animation should work in every VC

## Actual Behavior
Animation only works in initial VC

## Steps to Reproduce the Problem
Creating two VCs, connecting them, using a code like

```
let fromAnimation = AnimationType.from(direction: .left, offset: 80)
headingTextLabel.animate(animations: [fromAnimation], delay: 0, duration: 0.5)
mainTextView.animate(animations: [fromAnimation], delay: 0, duration: 0.5)
continueButton.animate(animations: [fromAnimation], delay: 0.2, duration: 0.5)
```

and see the animation only on the initial VC

## Specifications

  - Xcode-Version: Xcode Version 11.3.1 (11C504)
  - iOS-Version: iOS 13

**Comment by marcosgriselli** [comment]
@d0hnj0e does this happen on `viewDidLoad()`?

**Comment by d0hnj0e** [comment]
@marcosgriselli, yes. In `viewDidLoad()` I call a function which executes the code from above; moving the code directly to `viewDidLoad()` does not change the fact.

**Comment by marcosgriselli** [comment]
@d0hnj0e and it happens when pushing a `UIViewController` on a `UINavigationController`, right?

**Comment by d0hnj0e** [comment]
No, the segue is from an `UIViewController` to another `UIViewController`:

<img width="253" alt="Screenshot 2020-01-23 at 13 37 42" src="https://user-images.githubusercontent.com/9201403/72985116-8ec06500-3de5-11ea-9247-62645354e70e.png">

**Comment by marcosgriselli** [comment]
Got it, I'll review it in the upcoming days.

**Comment by d0hnj0e** [comment]
Thanks, Marcos! Very kind!

**Comment by d0hnj0e** [comment]
I solved the problem, @marcosgriselli:

If you present a `UIViewController` with any segue, you need to call the animation functions not within `viewDidLoad()` but rather `viewDidLayoutSubviews()`. The following code executes flawlessly and shows the animation as it should:

```
override func viewDidLayoutSubviews() {
         
        let fromAnimation = AnimationType.from(direction: .left, offset: 80)
        headingTextLabel.animate(animations: [fromAnimation], delay: 0, duration: 0.5)
        mainTextView.animate(animations: [fromAnimation], delay: 0, duration: 0.5)
        continueButton.animate(animations: [fromAnimation], delay: 0.2, duration: 0.5)
        
}
```

Maybe you could briefly update the [`README.md`](https://github.com/marcosgriselli/ViewAnimator/blob/master/README.md) accordingly. :) 

And: Thanks for your great work with this library!

**Comment by marcosgriselli** [comment]
Thanks @d0hnj0e! I'll make sure to add a presentation example on the demo app. I'll close the issue.
