### ISSUE TITLE
Support of timing functions

### ISSUE THREAD

**Issue by Narayane** [marcosgriselli/ViewAnimator#65]
Hi,

Would it be possible to support timing functions like https://github.com/cats-oss/Sica#easingfunctions in ViewAnimator?

Thanks for this library.

**Comment by marcosgriselli** [comment]
@Narayane I was thinking about that feature some time ago. How would it work? Do each element get a specific animation time?

**Comment by Narayane** [comment]
Potentially. I'll keep you in touch :)

**Comment by Narayane** [comment]
Hi @marcosgriselli,

I've tried to follow this [approach](https://medium.com/@joncardasis/better-ios-animations-with-catransaction-72a7425673a6#e543) but it doesn't work with your extension `UIView.animate()`...

Even when I add parameter `options: [.curveEaseInOut]` to your extension `UIView.animate()`, it doesn't seem take in account at runtime, move is the save with and without...

Do you have any idea on how to make it?

Thanks.

**Comment by marcosgriselli** [comment]
@Narayane the reason why the options don't work on that particular function is that the animation is using springs (https://developer.apple.com/documentation/uikit/uiview/1622594-animatewithduration). We need to create a new function that uses the `UIView` animation API that doesn't use springs. 

Here's what the function will look like: 

```swift 
 static func animate(views: [UIView],
                    animations: [Animation],
                    reversed: Bool = false,
                    initialAlpha: CGFloat = 0.0,
                    finalAlpha: CGFloat = 1.0,
                    delay: Double = 0,
                    animationInterval: TimeInterval = 0.05,
                    duration: TimeInterval = ViewAnimatorConfig.duration,
                    options: UIView.AnimationOptions = [],
                    completion: (() -> Void)? = nil) {
    
    guard views.count > 0 else {
        completion?()
        return
    }
    
    views.forEach { $0.alpha = initialAlpha }
    let dispatchGroup = DispatchGroup()
    for _ in 1...views.count { dispatchGroup.enter() }
    DispatchQueue.main.asyncAfter(deadline: .now() + delay) {
        for (index, view) in views.enumerated() {
            view.alpha = initialAlpha
            view.animate(animations: animations,
                         reversed: reversed,
                         initialAlpha: initialAlpha,
                         finalAlpha: finalAlpha,
                         delay: Double(index) * animationInterval,
                         duration: duration,
                         options: options,
                         completion: { dispatchGroup.leave() })
        }
    }
    
    dispatchGroup.notify(queue: .main) {
        completion?()
    }
}
```

I'll create a release later this week with support for this but for the moment that function should be enough to drop-in and use in your project.
