### ISSUE TITLE
ViewAnimator Pod is not installing

### ISSUE THREAD

**Issue by thejaa** [marcosgriselli/ViewAnimator#67]
pod "ViewAnimator" is not installing on existing project.Though it is installing on newly created project.

  - Version:Xcode11.1
  - Platform:OS Catalina

**Comment by marcosgriselli** [comment]
@thejaa what error are you getting?

**Comment by marcosgriselli** [comment]
@thejaa is the problem still persisting?

**Comment by thejaa** [comment]
@marcosgriselli sorry for the delay.

Pod is installing as expected.
