### ISSUE TITLE
Question: Use ViewAnimator for animations between two VCs

### ISSUE THREAD

**Issue by tylerswartz** [marcosgriselli/ViewAnimator#9]
Hi Marcos,  I love these transitions and would like to incorporate them on my new project. I'm having trouble using it to transition between two view controllers. Is it possible to do that with ViewAnimator or is it only for loading a view within a view controller?

Here is the way I'm doing my transition between the two view controllers right now:
```
// In VC1 call this func to transition to VC2
func goToVC2() {
    let storyBoard: UIStoryboard = UIStoryboard(name: "Main", bundle:nil)
    let VC2 = storyBoard.instantiateViewController(withIdentifier: "VC2") as! VC2
    self.present(VC2, animated: true, completion: nil)
}
```

**Comment by marcosgriselli** [comment]
Hey Tyler, what kind of transition do you have in mind? 

I'm planning on creating a library to use ViewAnimator for transitions in the near future.

**Comment by tylerswartz** [comment]
I was hoping to use the animation that is in the entire view gif in the readme. When I transition between to views, I want to remove all of the elements and then have the new elements animate in so that it appears to the user to be a single view.

I suppose I could use this library still and just have everything on a single view controller. I only have pages on the app so it wouldn't be too much code to manage in a single vc.

**Comment by marcosgriselli** [comment]
@tylerswartz That could be one solution. Also, take a look at custom viewcontroller transitions. You could create a transition where the first controller animates its cells then fades into the next one and that last one animates its cells in.

**Comment by marcosgriselli** [comment]
Closing as I'll plan to implement some transitions on a new Example app for #10
